"use client";

import { useState } from "react";

type Payment = { id: string; amount: string; status: string; receiptName?: string; receiptMime?: string; receiptData?: string; order: { orderNumber: string; buyerName: string; buyerPhone: string; total: string; deliveryAddress: string; createdAt: string } };

export default function AdminPage() {
  const [key, setKey] = useState(""); const [payments, setPayments] = useState<Payment[]>([]); const [message, setMessage] = useState(""); const [selected, setSelected] = useState<Payment | null>(null);
  async function load() { const response = await fetch("/api/admin/payments", { headers: { "x-admin-key": key } }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Дастрасӣ манъ аст."); setPayments(data.payments); setMessage(""); }
  async function decide(paymentId: string, decision: "APPROVED" | "REJECTED") { const response = await fetch("/api/admin/payments", { method: "POST", headers: { "Content-Type": "application/json", "x-admin-key": key }, body: JSON.stringify({ paymentId, decision }) }); const data = await response.json(); setMessage(data.error ?? (response.ok ? "Қарор сабт шуд." : "Хато рӯй дод.")); if (response.ok) { setSelected(null); load(); } }
  return <main className="simplePage"><section className="adminCard"><a href="/">← Ба сайт</a><h1>Панели пардохтҳо</h1><div className="adminLogin"><input type="password" placeholder="ADMIN_PANEL_KEY" value={key} onChange={(e) => setKey(e.target.value)} /><button className="submit" onClick={load}>Кушодан</button></div>{message && <div className="message">{message}</div>}<div className="paymentList">{payments.map((payment) => <article className="paymentItem" key={payment.id}><div><b>{payment.order.orderNumber}</b><p>{payment.order.buyerName} · {payment.order.buyerPhone}</p><small>{payment.amount} сомонӣ · {payment.receiptName ?? "бе расид"}</small></div><div className="actions"><button onClick={() => setSelected(payment)}>Дидани расид</button><button className="approve" onClick={() => decide(payment.id, "APPROVED")}>Тасдиқ</button><button className="reject" onClick={() => decide(payment.id, "REJECTED")}>Рад</button></div></article>)}{!payments.length && <div className="empty">Пардохти интизори санҷиш нест.</div>}</div>{selected && <div className="receiptModal" onClick={() => setSelected(null)}><div onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}>×</button><h2>{selected.order.orderNumber}</h2>{selected.receiptMime === "application/pdf" ? <a href={selected.receiptData} target="_blank" rel="noreferrer">Кушодани PDF</a> : <img src={selected.receiptData} alt="Расиди пардохт" />}</div></div>}</section></main>;
}
