"use client";
import { useState } from "react";
type Product = { id:string; name:string; price:string; stock:number; unit:string; isActive:boolean; isApproved:boolean; store:{name:string}; category:{name:string} };
type Lookup = { id:string; name:string };
export default function CatalogAdmin(){ const [key,setKey]=useState(""); const [products,setProducts]=useState<Product[]>([]); const [stores,setStores]=useState<Lookup[]>([]); const [categories,setCategories]=useState<Lookup[]>([]); const [form,setForm]=useState({name:"",slug:"",price:"",stock:"",unit:"дона",storeId:"",categoryId:""}); const [message,setMessage]=useState("");
 async function load(){ const headers={"x-admin-key":key}; const [p,c]=await Promise.all([fetch("/api/admin/products",{headers}),fetch("/api/admin/catalog",{headers})]); const pd=await p.json(); const cd=await c.json(); if(!p.ok)return setMessage(pd.error??"Дастрасӣ манъ аст."); setProducts(pd.products); setStores(cd.stores??[]); setCategories(cd.categories??[]); }
 async function create(e:React.FormEvent){e.preventDefault();const response=await fetch("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json","x-admin-key":key},body:JSON.stringify({...form,price:Number(form.price),stock:Number(form.stock),isApproved:true})});const data=await response.json();setMessage(data.error??(response.ok?"Маҳсулот илова шуд.":"Хато рӯй дод."));if(response.ok){setForm({name:"",slug:"",price:"",stock:"",unit:"дона",storeId:form.storeId,categoryId:form.categoryId});load();}}
 async function toggle(product:Product,field:"isActive"|"isApproved"){await fetch("/api/admin/products",{method:"PATCH",headers:{"Content-Type":"application/json","x-admin-key":key},body:JSON.stringify({id:product.id,[field]:!product[field]})});load();}
 return <main className="simplePage"><section className="adminCard"><a href="/admin">← Панели админ</a><h1>Идоракунии маҳсулот</h1><div className="adminLogin"><input type="password" placeholder="ADMIN_PANEL_KEY" value={key} onChange={e=>setKey(e.target.value)}/><button className="submit" onClick={load}>Кушодан</button></div>{message&&<div className="message">{message}</div>}<form className="productForm" onSubmit={create}><input required placeholder="Номи маҳсулот" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required pattern="[a-z0-9-]{2,100}" placeholder="slug-example" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><input required type="number" min="0" step="0.01" placeholder="Нарх" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input required type="number" min="0" step="1" placeholder="Захира" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input required placeholder="Воҳид: дона, кг, метр" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><select required value={form.storeId} onChange={e=>setForm({...form,storeId:e.target.value})}><option value="">Мағозаро интихоб кунед</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Категорияро интихоб кунед</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="submit">Илова кардани маҳсулот</button></form><div className="paymentList">{products.map(p=><article className="paymentItem" key={p.id}><div><b>{p.name}</b><p>{p.price} сомонӣ · {p.stock} {p.unit}</p><small>{p.store.name} · {p.category.name}</small></div><div className="actions"><button onClick={()=>toggle(p,"isApproved")}>{p.isApproved?"Пинҳон кардан":"Тасдиқ кардан"}</button><button onClick={()=>toggle(p,"isActive")}>{p.isActive?"Ғайрифаъол":"Фаъол"}</button></div></article>)}</div></section></main>;
}
